apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-delivery
  labels:
    app: spring-k8s-delivery

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: spring-k8s-delivery

  template:
    metadata:
      labels:
        app: spring-k8s-delivery

    spec:
      containers:
        - name: spring-k8s-delivery
          image: spring-k8s-delivery:0.2.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: spring-k8s-delivery-config

            - secretRef:
                name: spring-k8s-delivery-secret

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"